// ** Next Imports
import { Metadata } from "next";

// ** Context
import { AuthProvider } from "@/context/AuthProvider";
import ReactQueryProvider from "@/context/ReactQueryProvider";

// ** Library Imports
import { Toaster } from "@/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";

// ** Lib
import { raleway, playfair } from "@/lib/font";

// ** CSS
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <body className={`${playfair.variable} ${raleway.variable} antialiased`}>
        <NextTopLoader
          height={3}
          color="hsl(var(--primary))"
          showSpinner={false}
        />
        <Toaster />
        <ReactQueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
